web-apps/django/learn_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

web-apps/django/learn_log/learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # Home page
    path('', views.index, name='index'),
    # Topics home
    path('topics/', views.topics, name='topics'),
]

web-apps/django/learn_log/learning_logs/models.py
from django.db import models

class Topic(models.Model):
    """Topic that user follows"""
    # Define some attributes
    # CharField good for small amount of text
    text = models.CharField(max_length=200)
    # auto_now_add=True automatically sets this to current datetime of init
    date_added = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        """Return string representation of the model"""
        return self.text

class Entry(models.Model):
    """Something specific learned about a topic"""
    # pulls from Topic model and if Topic model is deleted, so is this entry
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    # holds extra info about model
    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        return self.text[:50] + "..."

web-apps/django/learn_log/learning_logs/views.py
from django.shortcuts import render
from .models import Topic

def index(request):
    """The home page for Learning Log"""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """List all topics from Learning Log"""
    topics = Topic.objects.order_by('date_added')
    # Store queryset in topics
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

web-apps/django/learn_log/learning_logs/templates/learning_logs/base.html
<!-- Parent template, every other template will inherit from base.html -->
<p>
  <!-- if you want to update url, do so in urls.py and will automatically update here -->
  <a href="{% url 'learning_logs:index' %}">Learning Log</a>
  <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>

{% block content %}{% endblock content %}

web-apps/django/learn_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p> Learning Log helps you keep track of your learning, for any topic you're learning about. </p>
{% endblock content %}

web-apps/django/learn_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block content %}
  <p>Topics</p>
  <ul>
    {% for topic in topics %}
      <!-- braces to indicate template variable -->
      <li>{{ topic }}</li>
    {% empty %}
        <li>No topics have been added yet.</li>
    {% endfor %}
  </ul>
{% endblock content %}